# Stage 1: Install dependencies
FROM python:3.14-slim AS builder

WORKDIR /build

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    --prefix=/install \
    -r requirements.txt


# Stage 2: Create the final runtime image
FROM python:3.14-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY All_Diets.csv .
COPY data_analysis.py .

CMD ["python", "data_analysis.py"]
